# ==============================================================================
# Merged Lakeflow Source: ramp
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    Literal,
    Sequence,
    TypedDict,
    cast,
)
import json
import re
import time

from email.utils import parsedate_to_datetime
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import urlsplit
import base64
import random
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/ramp/ramp_schemas.py
    ########################################################

    MONEY_DECIMAL = DecimalType(38, 9)

    CURRENCY_AMOUNT_STRUCT = StructType(
        [
            StructField("amount", LongType(), True),
            StructField("currency_code", StringType(), True),
            StructField("minor_unit_conversion_rate", LongType(), True),
        ]
    )

    API_AMOUNT_STRUCT = StructType(
        [
            StructField("currency", StringType(), True),
            StructField("value", LongType(), True),
        ]
    )

    SIGNED_AMOUNT_STRUCT = StructType(
        [
            StructField("currency", StringType(), True),
            StructField("value", LongType(), True),
        ]
    )

    TRANSACTION_CARD_HOLDER_STRUCT = StructType(
        [
            StructField("department_id", StringType(), True),
            StructField("department_name", StringType(), True),
            StructField("employee_id", StringType(), True),
            StructField("first_name", StringType(), True),
            StructField("last_name", StringType(), True),
            StructField("location_id", StringType(), True),
            StructField("location_name", StringType(), True),
            StructField("user_id", StringType(), True),
        ]
    )

    TRANSACTION_DECLINE_DETAILS_STRUCT = StructType(
        [
            StructField("amount", MONEY_DECIMAL, True),
            StructField("declined_amount", SIGNED_AMOUNT_STRUCT, True),
            StructField("reason", StringType(), True),
        ]
    )

    MERCHANT_LOCATION_STRUCT = StructType(
        [
            StructField("city", StringType(), True),
            StructField("country", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("state", StringType(), True),
        ]
    )

    REIMBURSEMENT_TRACE_ID_STRUCT = StructType(
        [
            StructField("descriptor", StringType(), True),
            StructField("trace_id", StringType(), True),
        ]
    )

    ADDRESS_STRUCT = StructType(
        [
            StructField("address_line_1", StringType(), True),
            StructField("address_line_2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("country", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("state", StringType(), True),
        ]
    )

    VENDOR_ADDRESS_STRUCT = StructType(
        [
            StructField("address_line_1", StringType(), True),
            StructField("address_line_2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("country", StringType(), True),
            StructField("id", StringType(), True),
            StructField("is_default", BooleanType(), True),
            StructField("postal_code", StringType(), True),
            StructField("state", StringType(), True),
        ]
    )

    DEFAULT_PAYMENT_METHOD_STRUCT = StructType(
        [
            # The policy is a discriminated union (address/bank-account/card), so
            # it remains canonical JSON while the stable update source is typed.
            StructField("policy", StringType(), True),
            StructField("update_source", StringType(), True),
        ]
    )


    TRANSACTIONS_SCHEMA = StructType(
        [
            StructField("accounting_categories", StringType(), True),
            StructField("accounting_date", TimestampType(), True),
            StructField("accounting_field_selections", StringType(), True),
            StructField("all_requirements_met_and_approved", BooleanType(), True),
            StructField("amount", MONEY_DECIMAL, True),
            StructField("attendees", StringType(), True),
            StructField("card_holder", TRANSACTION_CARD_HOLDER_STRUCT, True),
            StructField("card_id", StringType(), True),
            StructField("card_present", BooleanType(), True),
            StructField("currency_code", StringType(), True),
            StructField("decline_details", TRANSACTION_DECLINE_DETAILS_STRUCT, True),
            StructField("disputes", StringType(), True),
            StructField("entity_id", StringType(), True),
            StructField("fund_id", StringType(), True),
            StructField("id", StringType(), False),
            StructField("limit_id", StringType(), True),
            StructField("line_items", StringType(), True),
            StructField("memo", StringType(), True),
            StructField("merchant_category_code", StringType(), True),
            StructField("merchant_category_code_description", StringType(), True),
            StructField("merchant_data", StringType(), True),
            StructField("merchant_descriptor", StringType(), True),
            StructField("merchant_id", StringType(), True),
            StructField("merchant_location", MERCHANT_LOCATION_STRUCT, True),
            StructField("merchant_name", StringType(), True),
            StructField("minor_unit_conversion_rate", LongType(), True),
            StructField("network_merchant_id", StringType(), True),
            StructField("original_transaction_amount", CURRENCY_AMOUNT_STRUCT, True),
            StructField("original_transaction_id", StringType(), True),
            StructField("policy_violations", StringType(), True),
            StructField("receipts", ArrayType(StringType(), True), True),
            StructField(
                "requires_accounting_vendor_creation_to_sync",
                BooleanType(),
                True,
            ),
            StructField("settlement_date", TimestampType(), True),
            StructField("sk_category_id", LongType(), True),
            StructField("sk_category_name", StringType(), True),
            StructField("spend_program_id", StringType(), True),
            StructField("state", StringType(), True),
            StructField("statement_id", StringType(), True),
            StructField("sync_status", StringType(), True),
            StructField("synced_at", TimestampType(), True),
            StructField("trip_id", StringType(), True),
            StructField("trip_name", StringType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("user_transaction_time", TimestampType(), True),
            StructField("tenant_id", StringType(), False),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )

    REIMBURSEMENTS_SCHEMA = StructType(
        [
            StructField("accounting_date", TimestampType(), True),
            StructField("accounting_field_selections", StringType(), True),
            StructField("approved_at", TimestampType(), True),
            StructField("attendees", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("direction", StringType(), True),
            StructField("distance", MONEY_DECIMAL, True),
            StructField("employee_id", StringType(), True),
            StructField("end_location", StringType(), True),
            StructField("entity_amount", API_AMOUNT_STRUCT, True),
            StructField("entity_id", StringType(), True),
            StructField("fund_id", StringType(), True),
            StructField("id", StringType(), False),
            StructField("line_items", StringType(), True),
            StructField("memo", StringType(), True),
            StructField("merchant", StringType(), True),
            StructField("merchant_amount", API_AMOUNT_STRUCT, True),
            StructField("merchant_id", StringType(), True),
            StructField("payee_amount", API_AMOUNT_STRUCT, True),
            StructField("payment_batch_id", StringType(), True),
            StructField("payment_id", StringType(), True),
            StructField("payment_processed_at", TimestampType(), True),
            StructField("receipts", ArrayType(StringType(), True), True),
            StructField("spend_limit_id", StringType(), True),
            StructField("start_location", StringType(), True),
            StructField("state", StringType(), True),
            StructField("submitted_at", TimestampType(), True),
            StructField("sync_status", StringType(), True),
            StructField("synced_at", TimestampType(), True),
            StructField("trace_id", REIMBURSEMENT_TRACE_ID_STRUCT, True),
            StructField("transaction_date", DateType(), True),
            StructField("trip_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("user_email", StringType(), True),
            StructField("user_full_name", StringType(), True),
            StructField("user_id", StringType(), True),
            StructField("waypoints", ArrayType(StringType(), True), True),
            StructField("tenant_id", StringType(), False),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )

    VENDORS_SCHEMA = StructType(
        [
            StructField("accounting_vendor_remote_id", StringType(), True),
            StructField("address", ADDRESS_STRUCT, True),
            StructField("addresses", ArrayType(VENDOR_ADDRESS_STRUCT, True), True),
            StructField("billing_frequency", StringType(), True),
            StructField("contacts", ArrayType(StringType(), True), True),
            StructField("country", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("default_entity_id", StringType(), True),
            StructField("default_payment_method", DEFAULT_PAYMENT_METHOD_STRUCT, True),
            StructField("description", StringType(), True),
            StructField("external_vendor_id", StringType(), True),
            StructField("federal_tax_classification", StringType(), True),
            StructField("id", StringType(), False),
            StructField("is_active", BooleanType(), True),
            StructField("is_deletable", BooleanType(), True),
            StructField("merchant_id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("name_legal", StringType(), True),
            StructField("parent_vendor_id", StringType(), True),
            StructField("sk_category_id", LongType(), True),
            StructField("sk_category_name", StringType(), True),
            StructField("state", StringType(), True),
            StructField("subsidiary", ArrayType(StringType(), True), True),
            StructField("tax_address", ADDRESS_STRUCT, True),
            StructField("total_spend_all_time", CURRENCY_AMOUNT_STRUCT, True),
            StructField("total_spend_last_30_days", CURRENCY_AMOUNT_STRUCT, True),
            StructField("total_spend_last_365_days", CURRENCY_AMOUNT_STRUCT, True),
            StructField("total_spend_ytd", CURRENCY_AMOUNT_STRUCT, True),
            StructField("vendor_owner_id", StringType(), True),
            StructField("vendor_type", StringType(), True),
            StructField("tenant_id", StringType(), False),
            # Ramp filters vendors by updated_at but omits updated_at from rows.
            # M3/M4 will stamp the fully-drained update-window boundary here.
            StructField("_ramp_window_end", TimestampType(), True),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )

    USERS_SCHEMA = StructType(
        [
            StructField("business_id", StringType(), True),
            StructField("custom_fields", StringType(), True),
            StructField("department_id", StringType(), True),
            StructField("email", StringType(), True),
            StructField("employee_id", StringType(), True),
            StructField("entity_id", StringType(), True),
            StructField("first_name", StringType(), True),
            StructField("id", StringType(), False),
            StructField("is_manager", BooleanType(), True),
            StructField("last_name", StringType(), True),
            StructField("location_id", StringType(), True),
            StructField("manager_id", StringType(), True),
            StructField("phone", StringType(), True),
            StructField("role", StringType(), True),
            StructField("scheduled_deactivation_date", TimestampType(), True),
            StructField("scheduled_invitation_date", TimestampType(), True),
            StructField("status", StringType(), True),
            StructField("tenant_id", StringType(), False),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )

    DEPARTMENTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("tenant_id", StringType(), False),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )

    LOCATIONS_SCHEMA = StructType(
        [
            StructField("entity_id", StringType(), True),
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("tenant_id", StringType(), False),
            StructField("_ramp_extracted_at", TimestampType(), False),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "transactions": TRANSACTIONS_SCHEMA,
        "reimbursements": REIMBURSEMENTS_SCHEMA,
        "vendors": VENDORS_SCHEMA,
        "users": USERS_SCHEMA,
        "departments": DEPARTMENTS_SCHEMA,
        "locations": LOCATIONS_SCHEMA,
    }

    TABLE_METADATA: dict[str, dict] = {
        "transactions": {
            "primary_keys": ["tenant_id", "id"],
            "ingestion_type": "snapshot",
        },
        "reimbursements": {
            "primary_keys": ["tenant_id", "id"],
            "ingestion_type": "snapshot",
        },
        "vendors": {
            "primary_keys": ["tenant_id", "id"],
            "cursor_field": "_ramp_window_end",
            "ingestion_type": "cdc",
        },
        "users": {
            "primary_keys": ["tenant_id", "id"],
            "ingestion_type": "snapshot",
        },
        "departments": {
            "primary_keys": ["tenant_id", "id"],
            "ingestion_type": "snapshot",
        },
        "locations": {
            "primary_keys": ["tenant_id", "id"],
            "ingestion_type": "snapshot",
        },
    }

    SUPPORTED_TABLES: tuple[str, ...] = tuple(TABLE_SCHEMAS)

    # Fields M3 must serialize deterministically before emission.
    JSON_STRING_FIELDS: dict[str, frozenset[str]] = {
        "transactions": frozenset(
            {
                "accounting_categories",
                "accounting_field_selections",
                "attendees",
                "disputes",
                "line_items",
                "merchant_data",
                "policy_violations",
            }
        ),
        "reimbursements": frozenset(
            {
                "accounting_field_selections",
                "attendees",
                "line_items",
            }
        ),
        "vendors": frozenset(),
        "users": frozenset({"custom_fields"}),
        "departments": frozenset(),
        "locations": frozenset(),
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/ramp/ramp.py
    ########################################################

    Environment = Literal["production", "sandbox"]

    API_ROOTS: dict[Environment, str] = {
        "production": "https://api.ramp.com",
        "sandbox": "https://demo-api.ramp.com",
    }

    BUSINESS_ENDPOINT = "/developer/v1/business"
    OFFSET_VERSION = 1
    DEFAULT_PAGE_SIZE = 100
    MAX_PAGE_SIZE = 100
    DEFAULT_MAX_RECORDS_PER_BATCH = 5000
    DEFAULT_WINDOW_SECONDS = 86_400
    DEFAULT_LOOKBACK_SECONDS = 300
    HTTP_TIMEOUT_SECONDS = (10.0, 30.0)
    MAX_HTTP_ATTEMPTS = 5
    MAX_BACKOFF_SECONDS = 30.0
    MAX_PAGES_PER_TRIGGER = 100_000
    RETRIABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
    _SAFE_CONTEXT = re.compile(r"^[A-Za-z0-9_.:-]{1,128}$")


    class RampApiError(RuntimeError):
        """Sanitized Ramp transport, HTTP, or response-contract failure."""

        def __init__(
            self,
            message: str,
            *,
            status_code: int | None = None,
            error_code: str | None = None,
            trace_id: str | None = None,
        ) -> None:
            details = [message]
            if status_code is not None:
                details.append(f"status={status_code}")
            if error_code:
                details.append(f"error_code={error_code}")
            if trace_id:
                details.append(f"trace_id={trace_id}")
            super().__init__("; ".join(details))
            self.status_code = status_code
            self.error_code = error_code
            self.trace_id = trace_id


    class RampOffset(TypedDict, total=False):
        """Versioned, tenant-safe checkpoint envelope used by Ramp reads."""

        version: int
        table: str
        tenant_id: str
        environment: Environment
        flow: Literal["records"]
        phase: Literal["initial", "incremental", "complete"]
        cursor: str
        upper_bound: str
        continuation: str
        previous_continuation: str
        page_count: int
        window_start: str
        window_end: str
        lookback_applied: bool
        fanout_index: int


    @dataclass(frozen=True)
    class RampTableContract:
        """Immutable request and cursor contract for one supported table."""

        endpoint: str
        scope: str
        default_params: tuple[tuple[str, str], ...] = ()
        fanout: tuple[tuple[str, str], ...] = ()
        cursor_filter: str | None = None
        upper_cursor_filter: str | None = None
        lower_bound_exclusive: bool | None = None
        upper_bound_inclusive: bool | None = None


    TABLE_CONTRACTS: dict[str, RampTableContract] = {
        "transactions": RampTableContract(
            endpoint="/developer/v1/transactions",
            scope="transactions:read",
            default_params=(("state", "ALL"),),
        ),
        "reimbursements": RampTableContract(
            endpoint="/developer/v1/reimbursements",
            scope="reimbursements:read",
            fanout=(
                ("direction", "BUSINESS_TO_USER"),
                ("direction", "USER_TO_BUSINESS"),
            ),
        ),
        "vendors": RampTableContract(
            endpoint="/developer/v1/vendors",
            scope="vendors:read",
            default_params=(("include_draft", "true"),),
            cursor_filter="from_updated_at",
            upper_cursor_filter="to_updated_at",
            lower_bound_exclusive=True,
            upper_bound_inclusive=True,
        ),
        "users": RampTableContract(
            endpoint="/developer/v1/users",
            scope="users:read",
            fanout=(
                ("status", "USER_ACTIVE"),
                ("status", "USER_DRAFT"),
                ("status", "USER_INACTIVE"),
                ("status", "USER_SUSPENDED"),
            ),
        ),
        "departments": RampTableContract(
            endpoint="/developer/v1/departments",
            scope="departments:read",
        ),
        "locations": RampTableContract(
            endpoint="/developer/v1/locations",
            scope="locations:read",
        ),
    }

    TABLE_ENDPOINTS: dict[str, str] = {
        table_name: contract.endpoint for table_name, contract in TABLE_CONTRACTS.items()
    }

    TABLE_SCOPES: dict[str, str] = {
        table_name: contract.scope for table_name, contract in TABLE_CONTRACTS.items()
    }

    DOWNGRADED_SNAPSHOT_TABLES = frozenset({"transactions", "reimbursements"})

    TABLE_OPTION_ALLOWLIST: dict[str, frozenset[str]] = {
        "transactions": frozenset({"page_size"}),
        "reimbursements": frozenset({"page_size"}),
        "vendors": frozenset(
            {
                "lookback_seconds",
                "max_records_per_batch",
                "page_size",
                "window_seconds",
            }
        ),
        "users": frozenset({"page_size"}),
        "departments": frozenset({"page_size"}),
        "locations": frozenset({"page_size"}),
    }

    # Managed ingestion passes connection credentials and Databricks execution
    # metadata through the same Spark options mapping as table controls. Unity
    # Catalog has already restricted user-supplied table controls with the
    # connector's external_options_allowlist, so the presence of one of these
    # reserved markers means unrelated runtime keys must be ignored here.
    MANAGED_RUNTIME_OPTION_MARKERS = frozenset(
        {
            "connectionname",
            "databricks.connection",
            "dltpipelineid",
        }
    )

    DEFAULT_TABLE_OPTIONS: dict[str, dict[str, str]] = {
        "transactions": {"page_size": str(DEFAULT_PAGE_SIZE)},
        "reimbursements": {"page_size": str(DEFAULT_PAGE_SIZE)},
        "vendors": {
            "page_size": str(DEFAULT_PAGE_SIZE),
            "max_records_per_batch": str(DEFAULT_MAX_RECORDS_PER_BATCH),
            "window_seconds": str(DEFAULT_WINDOW_SECONDS),
            "lookback_seconds": str(DEFAULT_LOOKBACK_SECONDS),
        },
        "users": {"page_size": str(DEFAULT_PAGE_SIZE)},
        "departments": {"page_size": str(DEFAULT_PAGE_SIZE)},
        "locations": {"page_size": str(DEFAULT_PAGE_SIZE)},
    }


    class RampApiClient:  # pylint: disable=too-many-instance-attributes
        """Hardened bearer-token client for Ramp's read-only Developer API."""

        def __init__(
            self,
            options: dict[str, str],
            *,
            session: Any | None = None,
            sleep: Callable[[float], None] = time.sleep,
            jitter: Callable[[], float] = random.random,
        ) -> None:
            raw_environment = options.get("environment", "production").strip().lower()
            if raw_environment not in API_ROOTS:
                supported = ", ".join(sorted(API_ROOTS))
                raise ValueError(f"Unsupported Ramp environment. Expected one of: {supported}")

            access_token = options.get("access_token", "").strip()
            if not access_token:
                raise ValueError(
                    "Ramp connector requires an OAuth access_token injected by "
                    "the Unity Catalog M2M connection"
                )

            self.environment = cast(Environment, raw_environment)
            self.base_url = API_ROOTS[self.environment]
            self._access_token = access_token
            self.timeout_seconds = HTTP_TIMEOUT_SECONDS
            self._session = session or requests.Session()
            self._session.headers.update(self.authorization_headers())
            self._sleep = sleep
            self._jitter = jitter
            self._business_id: str | None = None

        def authorization_headers(self) -> dict[str, str]:
            """Build standard Ramp JSON request headers without logging them."""
            return {
                "Accept": "application/json",
                "Authorization": f"Bearer {self._access_token}",
            }

        def request_json(
            self,
            method: str,
            path_or_url: str,
            *,
            params: dict[str, str] | None = None,
        ) -> Any:
            """Issue a bounded request and return precision-preserving decoded JSON."""
            normalized_method = method.upper()
            if normalized_method != "GET":
                raise ValueError(f"Unsupported Ramp HTTP method: {normalized_method}")

            url = self._resolve_url(path_or_url)
            for attempt in range(MAX_HTTP_ATTEMPTS):
                try:
                    response = self._session.request(
                        normalized_method,
                        url,
                        params=params,
                        timeout=self.timeout_seconds,
                        allow_redirects=False,
                    )
                except (requests.ConnectionError, requests.Timeout):
                    if attempt == MAX_HTTP_ATTEMPTS - 1:
                        raise RampApiError("Ramp transport failed after bounded retries") from None
                    self._sleep(self._backoff_seconds(attempt, None))
                    continue

                if 200 <= response.status_code < 300:
                    try:
                        return response.json(parse_float=Decimal)
                    except (TypeError, ValueError):
                        raise RampApiError(
                            "Ramp response was not valid JSON",
                            status_code=response.status_code,
                            trace_id=self._safe_context(response.headers.get("x-trace-id")),
                        ) from None

                if response.status_code in RETRIABLE_STATUS_CODES and attempt < MAX_HTTP_ATTEMPTS - 1:
                    retry_after = response.headers.get("Retry-After")
                    self._sleep(self._backoff_seconds(attempt, retry_after))
                    continue

                raise self._http_error(response)

            raise RampApiError("Ramp request exhausted its retry policy")

        def iter_list(
            self,
            endpoint: str,
            *,
            params: dict[str, str] | None = None,
        ) -> Iterable[dict[str, Any]]:
            """Yield all list rows while validating each Ramp ``page.next`` URL."""
            target = endpoint
            request_params = dict(params) if params else None
            seen_continuations: set[str] = set()

            while True:
                data, next_url = self.get_list_page(target, params=request_params)
                request_params = None
                yield from data
                if next_url is None:
                    return
                if next_url in seen_continuations:
                    raise RampApiError("Ramp pagination returned a repeated continuation URL")
                seen_continuations.add(next_url)
                target = next_url

        def get_list_page(
            self,
            target: str,
            *,
            params: dict[str, str] | None = None,
        ) -> tuple[list[dict[str, Any]], str | None]:
            """Return one validated Ramp list page and its opaque continuation."""
            body = self.request_json("GET", target, params=params)
            if not isinstance(body, dict):
                raise RampApiError("Ramp list response must be a JSON object")

            data = body.get("data")
            if not isinstance(data, list):
                raise RampApiError("Ramp list response has invalid data")
            if any(not isinstance(record, dict) for record in data):
                raise RampApiError("Ramp list data contains a non-object record")

            page = body.get("page")
            if not isinstance(page, dict):
                raise RampApiError("Ramp list response has invalid page")
            next_url = page.get("next")
            if next_url is not None:
                if not isinstance(next_url, str) or not next_url:
                    raise RampApiError("Ramp list response has invalid page.next")
                self._validate_continuation_url(next_url)
            return data, next_url

        def get_business_id(self) -> str:
            """Resolve and cache the immutable tenant ID for this authenticated app."""
            if self._business_id is not None:
                return self._business_id

            body = self.request_json("GET", BUSINESS_ENDPOINT)
            business_id = body.get("id") if isinstance(body, dict) else None
            if not isinstance(business_id, str) or not business_id.strip():
                raise RampApiError("Ramp business id was missing or invalid")
            self._business_id = business_id.strip()
            return self._business_id

        def _resolve_url(self, path_or_url: str) -> str:
            if path_or_url.startswith("https://") or path_or_url.startswith("http://"):
                self._validate_continuation_url(path_or_url)
                return path_or_url
            if not path_or_url.startswith("/developer/v1/"):
                raise ValueError("Ramp API path must start with /developer/v1/")
            return f"{self.base_url}{path_or_url}"

        def _validate_continuation_url(self, url: str) -> None:
            candidate = urlsplit(url)
            expected = urlsplit(self.base_url)
            if candidate.scheme != "https":
                raise RampApiError("Ramp continuation URL must use HTTPS")
            if candidate.netloc != expected.netloc:
                raise RampApiError("Ramp continuation URL has an unexpected host")
            if not candidate.path.startswith("/developer/v1/"):
                raise RampApiError("Ramp continuation URL has an unexpected path")
            if ".." in candidate.path.split("/"):
                raise RampApiError("Ramp continuation URL has an unsafe path")
            if candidate.fragment:
                raise RampApiError("Ramp continuation URL must not contain a fragment")

        def _backoff_seconds(self, attempt: int, retry_after: str | None) -> float:
            parsed_retry_after = self._parse_retry_after(retry_after)
            if parsed_retry_after is not None:
                return min(MAX_BACKOFF_SECONDS, parsed_retry_after)
            base = min(MAX_BACKOFF_SECONDS, float(2**attempt))
            return min(MAX_BACKOFF_SECONDS, base * (1.0 + 0.25 * self._jitter()))

        @staticmethod
        def _parse_retry_after(value: str | None) -> float | None:
            if not value:
                return None
            try:
                return max(0.0, float(value))
            except ValueError:
                try:
                    retry_at = parsedate_to_datetime(value)
                except (TypeError, ValueError, OverflowError):
                    return None
                if retry_at.tzinfo is None:
                    retry_at = retry_at.replace(tzinfo=timezone.utc)
                return max(0.0, (retry_at - datetime.now(timezone.utc)).total_seconds())

        @classmethod
        def _http_error(cls, response: requests.Response) -> RampApiError:
            error_code = None
            try:
                body = response.json()
            except (TypeError, ValueError):
                body = None
            if isinstance(body, dict):
                error_code = cls._safe_context(body.get("error_code"))
            return RampApiError(
                "Ramp API request failed",
                status_code=response.status_code,
                error_code=error_code,
                trace_id=cls._safe_context(response.headers.get("x-trace-id")),
            )

        @staticmethod
        def _safe_context(value: Any) -> str | None:
            if isinstance(value, str) and _SAFE_CONTEXT.fullmatch(value):
                return value
            return None


    class RampLakeflowConnect(LakeflowConnect):
        """Lakeflow connector for complete snapshots and bounded vendor changes."""

        def __init__(
            self,
            options: dict[str, str],
            *,
            api_client: Any | None = None,
            now: Callable[[], datetime] | None = None,
        ) -> None:
            super().__init__(options)
            self._api = api_client or RampApiClient(options)
            current_time = (now or (lambda: datetime.now(timezone.utc)))()
            if current_time.tzinfo is None:
                raise ValueError("Ramp connector clock must return a timezone-aware datetime")
            self.initial_snapshot_upper_bound = self._format_timestamp(current_time)

        def list_tables(self) -> list[str]:
            """Return the six M1-selected Ramp tables in stable order."""
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            self._validate_table_options(table_name, table_options)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            self._validate_table_options(table_name, table_options)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict | None]:
            """Read a complete snapshot or one bounded, checkpointable vendor batch."""
            self._validate_table(table_name)
            self._validate_table_options(table_name, table_options)
            if start_offset is None:
                start_offset = {}
            elif not isinstance(start_offset, dict):
                raise ValueError("Ramp offset must be a dictionary")
            tenant_id = self._api.get_business_id()
            metadata = TABLE_METADATA[table_name]

            if metadata["ingestion_type"] == "snapshot":
                if start_offset:
                    raise ValueError(f"Snapshot table {table_name!r} does not accept an offset")
                rows = self._read_complete_snapshot(table_name, tenant_id, table_options)
                return iter(rows), None

            if table_name != "vendors":
                raise AssertionError(f"Unexpected incremental Ramp table: {table_name}")
            rows, offset = self._read_vendors(tenant_id, start_offset, table_options)
            return iter(rows), offset

        def _read_vendors(
            self,
            tenant_id: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[list[dict[str, Any]], RampOffset]:
            """Read one initial page group or one closed vendor update window."""
            if not start_offset:
                upper_bound = self.initial_snapshot_upper_bound
                return self._read_vendor_pages(
                    tenant_id=tenant_id,
                    table_options=table_options,
                    phase="initial",
                    committed_cursor=None,
                    upper_bound=upper_bound,
                    window_start=None,
                    window_end=upper_bound,
                    continuation=None,
                    previous_continuation=None,
                    page_count=0,
                )

            offset = self._validate_offset("vendors", tenant_id, start_offset)
            phase = offset["phase"]
            if phase == "initial":
                return self._read_vendor_pages(
                    tenant_id=tenant_id,
                    table_options=table_options,
                    phase="initial",
                    committed_cursor=None,
                    upper_bound=offset["upper_bound"],
                    window_start=None,
                    window_end=offset["upper_bound"],
                    continuation=offset["continuation"],
                    previous_continuation=offset.get("previous_continuation"),
                    page_count=offset.get("page_count", 0),
                )

            cursor = self._parse_timestamp("cursor", offset["cursor"])
            if phase == "complete":
                trigger_upper = self._parse_timestamp("upper_bound", self.initial_snapshot_upper_bound)
                if cursor >= trigger_upper:
                    return [], cast(RampOffset, dict(start_offset))
                lookback_seconds = self._option_int(
                    table_options, "lookback_seconds", DEFAULT_LOOKBACK_SECONDS
                )
                window_start = cursor - timedelta(seconds=lookback_seconds)
                upper_bound = trigger_upper
            else:
                upper_bound = self._parse_timestamp("upper_bound", offset["upper_bound"])
                if "continuation" in offset:
                    return self._read_vendor_pages(
                        tenant_id=tenant_id,
                        table_options=table_options,
                        phase="incremental",
                        committed_cursor=offset["cursor"],
                        upper_bound=offset["upper_bound"],
                        window_start=offset["window_start"],
                        window_end=offset["window_end"],
                        continuation=offset["continuation"],
                        previous_continuation=offset.get("previous_continuation"),
                        page_count=offset.get("page_count", 0),
                    )
                window_start = cursor

            window_seconds = self._option_int(table_options, "window_seconds", DEFAULT_WINDOW_SECONDS)
            window_end = min(cursor + timedelta(seconds=window_seconds), upper_bound)
            return self._read_vendor_pages(
                tenant_id=tenant_id,
                table_options=table_options,
                phase="incremental",
                committed_cursor=self._format_timestamp(cursor),
                upper_bound=self._format_timestamp(upper_bound),
                window_start=self._format_timestamp(window_start),
                window_end=self._format_timestamp(window_end),
                continuation=None,
                previous_continuation=None,
                page_count=0,
            )

        def _read_vendor_pages(  # pylint: disable=too-many-arguments,too-many-locals
            self,
            *,
            tenant_id: str,
            table_options: dict[str, str],
            phase: Literal["initial", "incremental"],
            committed_cursor: str | None,
            upper_bound: str,
            window_start: str | None,
            window_end: str,
            continuation: str | None,
            previous_continuation: str | None,
            page_count: int,
        ) -> tuple[list[dict[str, Any]], RampOffset]:
            """Drain only whole source pages and checkpoint the next opaque URL."""
            configured_page_size = self._option_int(table_options, "page_size", DEFAULT_PAGE_SIZE)
            max_records = self._option_int(
                table_options,
                "max_records_per_batch",
                DEFAULT_MAX_RECORDS_PER_BATCH,
            )
            effective_page_size = min(configured_page_size, max_records)
            contract = TABLE_CONTRACTS["vendors"]
            target = continuation or contract.endpoint
            request_params: dict[str, str] | None = None
            if continuation is None:
                request_params = dict(contract.default_params)
                request_params["page_size"] = str(effective_page_size)
                if phase == "incremental":
                    if window_start is None:
                        raise AssertionError("Incremental vendor window requires a lower bound")
                    request_params[cast(str, contract.cursor_filter)] = window_start
                request_params[cast(str, contract.upper_cursor_filter)] = window_end

            extracted_at = datetime.now(timezone.utc).isoformat()
            rows_by_id: dict[str, dict[str, Any]] = {}
            while True:
                page, next_url = self._api.get_list_page(target, params=request_params)
                request_params = None
                page_count += 1
                if page_count > MAX_PAGES_PER_TRIGGER:
                    raise RampApiError("Ramp pagination exceeded its bounded page limit")
                if len(page) > effective_page_size:
                    raise RampApiError("Ramp page exceeded the requested page_size")

                for record in page:
                    record_id = self._required_record_id("vendors", record)
                    rows_by_id[record_id] = self._normalize_record(
                        "vendors",
                        record,
                        tenant_id=tenant_id,
                        extracted_at=extracted_at,
                        window_end=window_end,
                    )

                if next_url is None:
                    return list(rows_by_id.values()), self._vendor_window_complete_offset(
                        tenant_id=tenant_id,
                        phase=phase,
                        upper_bound=upper_bound,
                        window_end=window_end,
                    )
                if next_url in (target, previous_continuation):
                    raise RampApiError("Ramp pagination returned a repeated continuation URL")

                if len(rows_by_id) + effective_page_size > max_records:
                    partial = self._base_offset(
                        tenant_id=tenant_id,
                        phase=phase,
                        upper_bound=upper_bound,
                    )
                    partial["continuation"] = next_url
                    partial["page_count"] = page_count
                    if target.startswith("https://"):
                        partial["previous_continuation"] = target
                    if phase == "incremental":
                        if committed_cursor is None or window_start is None:
                            raise AssertionError("Incremental vendor page lost its window state")
                        partial.update(
                            {
                                "cursor": committed_cursor,
                                "window_start": window_start,
                                "window_end": window_end,
                                "lookback_applied": True,
                            }
                        )
                    return list(rows_by_id.values()), partial

                previous_continuation = target if target.startswith("https://") else None
                target = next_url

        def _vendor_window_complete_offset(
            self,
            *,
            tenant_id: str,
            phase: Literal["initial", "incremental"],
            upper_bound: str,
            window_end: str,
        ) -> RampOffset:
            """Commit a fully drained initial snapshot or update window."""
            if phase == "initial" or self._parse_timestamp(
                "window_end", window_end
            ) >= self._parse_timestamp("upper_bound", upper_bound):
                return self._complete_offset(tenant_id, upper_bound)

            offset = self._base_offset(
                tenant_id=tenant_id,
                phase="incremental",
                upper_bound=upper_bound,
            )
            offset["cursor"] = window_end
            offset["lookback_applied"] = True
            return offset

        def _complete_offset(self, tenant_id: str, cursor: str) -> RampOffset:
            offset = self._base_offset(
                tenant_id=tenant_id,
                phase="complete",
                upper_bound=cursor,
            )
            offset["cursor"] = cursor
            return offset

        def _base_offset(
            self,
            *,
            tenant_id: str,
            phase: Literal["initial", "incremental", "complete"],
            upper_bound: str,
        ) -> RampOffset:
            return {
                "version": OFFSET_VERSION,
                "table": "vendors",
                "tenant_id": tenant_id,
                "environment": self._api.environment,
                "flow": "records",
                "phase": phase,
                "upper_bound": upper_bound,
            }

        def _read_complete_snapshot(
            self,
            table_name: str,
            tenant_id: str,
            table_options: dict[str, str],
        ) -> list[dict[str, Any]]:
            contract = TABLE_CONTRACTS[table_name]
            params = dict(contract.default_params)
            params["page_size"] = table_options.get("page_size", str(DEFAULT_PAGE_SIZE))
            request_params = [params]
            if contract.fanout:
                request_params = []
                for key, value in contract.fanout:
                    request_params.append({**params, key: value})

            extracted_at = datetime.now(timezone.utc).isoformat()
            rows_by_id: dict[str, dict[str, Any]] = {}
            for scoped_params in request_params:
                for record in self._api.iter_list(
                    contract.endpoint,
                    params=scoped_params,
                ):
                    record_id = self._required_record_id(table_name, record)
                    rows_by_id[record_id] = self._normalize_record(
                        table_name,
                        record,
                        tenant_id=tenant_id,
                        extracted_at=extracted_at,
                        window_end=None,
                    )
            return list(rows_by_id.values())

        @staticmethod
        def _required_record_id(table_name: str, record: dict[str, Any]) -> str:
            record_id = record.get("id") if isinstance(record, dict) else None
            if not isinstance(record_id, str) or not record_id.strip():
                raise RampApiError(f"Ramp {table_name} record is missing required id")
            return record_id

        def _normalize_record(
            self,
            table_name: str,
            record: dict[str, Any],
            *,
            tenant_id: str,
            extracted_at: str,
            window_end: str | None,
        ) -> dict[str, Any]:
            schema = TABLE_SCHEMAS[table_name]
            json_fields = JSON_STRING_FIELDS[table_name]
            row: dict[str, Any] = {}

            for field in schema.fields:
                name = field.name
                if name == "tenant_id":
                    row[name] = tenant_id
                    continue
                if name == "_ramp_extracted_at":
                    row[name] = extracted_at
                    continue
                if name == "_ramp_window_end":
                    row[name] = window_end
                    continue

                value = record.get(name)
                if name in json_fields and value is not None and not isinstance(value, str):
                    value = self._canonical_json(value)
                elif isinstance(field.dataType, StructType) and value == {}:
                    value = None
                row[name] = value

            payment_method = row.get("default_payment_method")
            if isinstance(payment_method, dict):
                normalized_method = dict(payment_method)
                policy = normalized_method.get("policy")
                if policy is not None and not isinstance(policy, str):
                    normalized_method["policy"] = self._canonical_json(policy)
                row["default_payment_method"] = normalized_method
            return row

        @staticmethod
        def _canonical_json(value: Any) -> str:
            return json.dumps(
                value,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=False,
                default=RampLakeflowConnect._json_default,
            )

        @staticmethod
        def _json_default(value: Any) -> str:
            if isinstance(value, Decimal):
                return str(value)
            raise TypeError(f"Unsupported canonical JSON value: {type(value).__name__}")

        def _validate_offset(
            self,
            table_name: str,
            tenant_id: str,
            offset: dict,
        ) -> RampOffset:
            if not isinstance(offset, dict):
                raise ValueError("Ramp offset must be a dictionary")
            if offset.get("table") != table_name:
                raise ValueError("Ramp offset table does not match the requested table")
            if offset.get("tenant_id") != tenant_id:
                raise ValueError("Ramp offset tenant does not match the authenticated business")
            if offset.get("environment") != self._api.environment:
                raise ValueError("Ramp offset environment does not match the connection")
            if offset.get("version") != OFFSET_VERSION:
                raise ValueError(f"Unsupported Ramp offset version; expected {OFFSET_VERSION}")
            if offset.get("flow") != "records":
                raise ValueError("Ramp offset flow must be records")
            phase = offset.get("phase")
            if phase not in {"initial", "incremental", "complete"}:
                raise ValueError("Ramp offset phase is invalid")

            upper_bound = self._required_offset_timestamp(offset, "upper_bound")
            self._validate_offset_phase(offset, phase, upper_bound)

            if "page_count" in offset:
                page_count = offset["page_count"]
                if not isinstance(page_count, int) or isinstance(page_count, bool) or page_count < 0:
                    raise ValueError("Ramp offset page_count must be a non-negative integer")
                if page_count >= MAX_PAGES_PER_TRIGGER:
                    raise ValueError("Ramp offset page_count exceeds the bounded page limit")
            if "previous_continuation" in offset:
                self._required_offset_string(offset, "previous_continuation")
            return cast(RampOffset, dict(offset))

        @classmethod
        def _validate_offset_phase(
            cls,
            offset: dict,
            phase: str,
            upper_bound: datetime,
        ) -> None:
            """Validate fields whose meaning depends on the checkpoint phase."""
            if phase == "initial":
                cls._required_offset_string(offset, "continuation")
            else:
                cursor = cls._required_offset_timestamp(offset, "cursor")
                if cursor > upper_bound:
                    raise ValueError("Ramp offset cursor cannot exceed upper_bound")
                if phase == "complete" and cursor != upper_bound:
                    raise ValueError("Ramp complete offset cursor must equal upper_bound")
                if phase == "incremental":
                    if cursor >= upper_bound:
                        raise ValueError("Ramp incremental offset cursor must precede upper_bound")
                    if offset.get("lookback_applied") is not True:
                        raise ValueError("Ramp incremental offset must record lookback_applied")
                    if "continuation" in offset:
                        cls._required_offset_string(offset, "continuation")
                        window_start = cls._required_offset_timestamp(offset, "window_start")
                        window_end = cls._required_offset_timestamp(offset, "window_end")
                        if window_start > window_end:
                            raise ValueError("Ramp offset window_start cannot exceed window_end")
                        if window_end > upper_bound or window_end <= cursor:
                            raise ValueError("Ramp offset window_end is outside the active bounds")

        @staticmethod
        def _required_offset_string(offset: dict, field: str) -> str:
            value = offset.get(field)
            if not isinstance(value, str) or not value:
                raise ValueError(f"Ramp offset {field} must be a non-empty string")
            return value

        @classmethod
        def _required_offset_timestamp(cls, offset: dict, field: str) -> datetime:
            return cls._parse_timestamp(field, cls._required_offset_string(offset, field))

        @staticmethod
        def _validate_table(table_name: str) -> None:
            if table_name not in TABLE_SCHEMAS:
                supported = ", ".join(SUPPORTED_TABLES)
                raise ValueError(
                    f"Unsupported Ramp table {table_name!r}. Supported tables: {supported}"
                )

        @staticmethod
        def _validate_table_options(table_name: str, table_options: dict[str, str]) -> None:
            allowed = TABLE_OPTION_ALLOWLIST[table_name]
            is_managed_runtime = bool(MANAGED_RUNTIME_OPTION_MARKERS & set(table_options))
            unknown = [] if is_managed_runtime else sorted(set(table_options) - allowed)
            if unknown:
                raise ValueError(
                    f"Unsupported options for Ramp table {table_name!r}: {unknown}. "
                    f"Allowed options: {sorted(allowed)}"
                )

            if "page_size" in allowed and "page_size" in table_options:
                RampLakeflowConnect._validate_int_option(
                    "page_size",
                    table_options["page_size"],
                    minimum=2,
                    maximum=MAX_PAGE_SIZE,
                )
            if "max_records_per_batch" in allowed and "max_records_per_batch" in table_options:
                RampLakeflowConnect._validate_int_option(
                    "max_records_per_batch",
                    table_options["max_records_per_batch"],
                    minimum=2,
                )
            if "window_seconds" in allowed and "window_seconds" in table_options:
                RampLakeflowConnect._validate_int_option(
                    "window_seconds", table_options["window_seconds"], minimum=1
                )
            if "lookback_seconds" in allowed and "lookback_seconds" in table_options:
                RampLakeflowConnect._validate_int_option(
                    "lookback_seconds",
                    table_options["lookback_seconds"],
                    minimum=0,
                )

        @staticmethod
        def _option_int(table_options: dict[str, str], name: str, default: int) -> int:
            return int(table_options.get(name, str(default)))

        @staticmethod
        def _validate_int_option(
            name: str,
            value: str,
            *,
            minimum: int,
            maximum: int | None = None,
        ) -> int:
            try:
                parsed = int(value)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"Ramp table option {name!r} must be an integer") from exc

            if parsed < minimum or (maximum is not None and parsed > maximum):
                upper = f" and {maximum}" if maximum is not None else ""
                raise ValueError(f"Ramp table option {name!r} must be between {minimum}{upper}")
            return parsed

        @staticmethod
        def _validate_timestamp(name: str, value: str) -> datetime:
            return RampLakeflowConnect._parse_timestamp(f"table option {name!r}", value)

        @staticmethod
        def _parse_timestamp(name: str, value: str) -> datetime:
            try:
                parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
            except (AttributeError, ValueError) as exc:
                raise ValueError(f"Ramp {name} must be an ISO 8601 timestamp") from exc
            if parsed.tzinfo is None:
                raise ValueError(f"Ramp {name} must include a UTC offset")
            return parsed.astimezone(timezone.utc)

        @staticmethod
        def _format_timestamp(value: datetime) -> str:
            return value.astimezone(timezone.utc).isoformat()


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = RampLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
